# Generated by Django 5.2.17 on 2026-08-20 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('salons', '0002_salon_address_salon_business_hours_and_more'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trigger', models.CharField(choices=[('BOOKING_CONFIRMATION', 'Booking confirmation'), ('APPOINTMENT_REMINDER', 'Appointment reminder'), ('FEEDBACK_REQUEST', 'Feedback request'), ('CANCELLATION_NOTICE', 'Cancellation / reschedule notice')], max_length=30)),
                ('channel', models.CharField(choices=[('WHATSAPP', 'WhatsApp')], default='WHATSAPP', max_length=10)),
                ('recipient', models.CharField(max_length=20)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('FAILED', 'Failed')], default='SENT', max_length=10)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='scheduling.appointment')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='crm.customer')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='salons.salon')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trigger', models.CharField(choices=[('BOOKING_CONFIRMATION', 'Booking confirmation'), ('APPOINTMENT_REMINDER', 'Appointment reminder'), ('FEEDBACK_REQUEST', 'Feedback request'), ('CANCELLATION_NOTICE', 'Cancellation / reschedule notice')], max_length=30)),
                ('body', models.TextField(help_text='Placeholders: {{ customer_name }}, {{ salon_name }}, {{ appointment_date }}, {{ appointment_time }}.')),
                ('is_active', models.BooleanField(default=True)),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='salons.salon')),
            ],
            options={
                'ordering': ['trigger'],
                'constraints': [models.UniqueConstraint(fields=('salon', 'trigger'), name='unique_message_template_per_trigger_per_salon')],
            },
        ),
    ]
