# Generated by Django 5.2.17 on 2026-08-19 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI'), ('CARD', 'Card'), ('BANK', 'Bank transfer'), ('ONLINE', 'Online'), ('ADVANCE', 'Advance (booking)')], max_length=10),
        ),
    ]
