from django.urls import path

from .views import (
    category_create_view,
    category_delete_view,
    category_edit_view,
    category_list_view,
    product_adjust_stock_view,
    product_create_view,
    product_delete_view,
    product_detail_view,
    product_edit_view,
    product_list_view,
    product_recipe_add_view,
    product_recipe_delete_view,
    purchase_add_item_view,
    purchase_create_view,
    purchase_detail_view,
    purchase_list_view,
    supplier_create_view,
    supplier_delete_view,
    supplier_edit_view,
    supplier_list_view,
)

urlpatterns = [
    path("products/", product_list_view, name="product-list"),
    path("products/new/", product_create_view, name="product-create"),
    path("products/<int:pk>/", product_detail_view, name="product-detail"),
    path("products/<int:pk>/edit/", product_edit_view, name="product-edit"),
    path("products/<int:pk>/delete/", product_delete_view, name="product-delete"),
    path("products/<int:pk>/adjust/", product_adjust_stock_view, name="product-adjust-stock"),
    path("products/<int:pk>/recipe/", product_recipe_add_view, name="product-recipe-add"),
    path(
        "products/<int:pk>/recipe/<int:recipe_pk>/delete/",
        product_recipe_delete_view,
        name="product-recipe-delete",
    ),
    path("product-categories/", category_list_view, name="product-category-list"),
    path("product-categories/new/", category_create_view, name="product-category-create"),
    path("product-categories/<int:pk>/edit/", category_edit_view, name="product-category-edit"),
    path("product-categories/<int:pk>/delete/", category_delete_view, name="product-category-delete"),
    path("suppliers/", supplier_list_view, name="supplier-list"),
    path("suppliers/new/", supplier_create_view, name="supplier-create"),
    path("suppliers/<int:pk>/edit/", supplier_edit_view, name="supplier-edit"),
    path("suppliers/<int:pk>/delete/", supplier_delete_view, name="supplier-delete"),
    path("purchases/", purchase_list_view, name="purchase-list"),
    path("purchases/new/", purchase_create_view, name="purchase-create"),
    path("purchases/<int:pk>/", purchase_detail_view, name="purchase-detail"),
    path("purchases/<int:pk>/items/", purchase_add_item_view, name="purchase-add-item"),
]
