# Generated by Django 5.2.17 on 2026-08-19 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_package_packageservice'),
        ('inventory', '0001_initial'),
        ('salons', '0002_salon_address_salon_business_hours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumption_recipes', to='inventory.product')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='salons.salon')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.service')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('service', 'product'), name='unique_service_product_recipe')],
            },
        ),
    ]
